- name: playbook
  hosts: localhost
  connection: local

  vars_prompt:
    - name: "ssh_passphrase"
      prompt: "Enter the passphrase for the SSH key"
   
  tasks:
    - name: generate SSH key "{{ssh_key_filename}}"
      user:
        name: root
        generate_ssh_key: yes
        ssh_key_type: rsa
        ssh_key_bits: 4096
        ssh_key_file: .ssh/id_rsa
        ssh_key_passphrase: "{{ssh_passphrase}}"
        force: no


    -  name: lauching ec2 instance
       ec2:
         image: ami-02e60be79e78fef21
         instance_type: t2.micro
         region: ap-south-1
         count: 1
         vpc_subnet_id: subnet-f4b6b69c
         group: default
         key_name: rajesh
         wait: yes
         assign_public_ip: yes
         user_data: "#! /bin/bash
                      sudo su root
                      cd /
                      sudo yum install wget -y
                      sudo yum install git -y"           
       register: myec2

    -  name: display instance details
       debug:
         msg: "{{ item.public_ip }}"
       loop: "{{ myec2.instances }}"

    - name: Copy using inline content
      copy:
        content: "[all_hosts]\n{{ item.public_ip }}"
        dest: /etc/ansible/hosts
      loop: "{{ myec2.instances }}"


